version: "2"

services:
  web:
    build: dev-scripts/docker/docker_build/drupal8/development
    volumes:
     - ./html:/var/www/html
     - ./dev-scripts/docker/dev-scripts/:/root/dev-scripts
     - ./vendor:/var/www/vendor
     - ./config/sync:/config/sync
    links:
     - db
     - mailcatcher
    environment:
     - VIRTUAL_HOST=social-enterprise.dev
     - DRUPAL_SETTINGS=development
    ports:
     - "80"
    network_mode: "bridge"
    container_name: social_enterprise_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data_enterprise:/var/lib/mysql
    ports:
      - "3308:3306"
    network_mode: "bridge"
    container_name: social_enterprise_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.social-enterprise.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: social_enterprise_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: social_enterprise_selenium

  behat:
    build: dev-scripts/docker/docker_build/drupal8/development
    volumes:
     - ./html/:/var/www/html
     - ./dev-scripts/docker/dev-scripts/:/root/dev-scripts
     - ./vendor:/var/www/vendor
     - ./config/sync:/config/sync
     - ./html/profiles/contrib/social/tests/behat/:/root/behat
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_enterprise_behat

  cron:
    build: dev-scripts/docker/docker_build/cron
    volumes:
     - ./html:/var/www/html
     - ./dev-scripts/docker/dev-scripts/:/root/dev-scripts
     - ./vendor:/var/www/vendor
     - ./config/sync:/config/sync
    links:
     - db
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: social_enterprise_cron

volumes:
  db_data_enterprise:
